// Class: ReadFisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Fisher::Fisher
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/14       [336398]
Creator        : ubuntuuser
Date           : Tue Jul 12 09:33:46 2016
Host           : Linux lamiak 3.2.0-37-generic #58-Ubuntu SMP Thu Jan 24 15:28:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/ubuntuuser/mmdd/higgsChallenge/higgs/work_in_progress/original_template_corrected
Training events: 24999
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
Method: "Fisher" [Discrimination method]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 30
DER_mass_MMC                  DER_mass_MMC                  DER_mass_MMC                  DER_mass_MMC                                                    'F'    [-999,921.419006348]
DER_mass_transverse_met_lep   DER_mass_transverse_met_lep   DER_mass_transverse_met_lep   DER_mass_transverse_met_lep                                     'F'    [0.0140000004321,690.075012207]
DER_mass_vis                  DER_mass_vis                  DER_mass_vis                  DER_mass_vis                                                    'F'    [7.32999992371,674.552978516]
DER_pt_h                      DER_pt_h                      DER_pt_h                      DER_pt_h                                                        'F'    [0,734.276977539]
DER_deltaeta_jet_jet          DER_deltaeta_jet_jet          DER_deltaeta_jet_jet          DER_deltaeta_jet_jet                                            'F'    [-999,7.96999979019]
DER_mass_jet_jet              DER_mass_jet_jet              DER_mass_jet_jet              DER_mass_jet_jet                                                'F'    [-999,3334.53393555]
DER_prodeta_jet_jet           DER_prodeta_jet_jet           DER_prodeta_jet_jet           DER_prodeta_jet_jet                                             'F'    [-999,14.7170000076]
DER_deltar_tau_lep            DER_deltar_tau_lep            DER_deltar_tau_lep            DER_deltar_tau_lep                                              'F'    [0.228000000119,5.44000005722]
DER_pt_tot                    DER_pt_tot                    DER_pt_tot                    DER_pt_tot                                                      'F'    [0,314.234008789]
DER_sum_pt                    DER_sum_pt                    DER_sum_pt                    DER_sum_pt                                                      'F'    [46.3790016174,1419.96496582]
DER_pt_ratio_lep_tau          DER_pt_ratio_lep_tau          DER_pt_ratio_lep_tau          DER_pt_ratio_lep_tau                                            'F'    [0.0900000035763,13.5530004501]
DER_met_phi_centrality        DER_met_phi_centrality        DER_met_phi_centrality        DER_met_phi_centrality                                          'F'    [-1.41400003433,1.41400003433]
DER_lep_eta_centrality        DER_lep_eta_centrality        DER_lep_eta_centrality        DER_lep_eta_centrality                                          'F'    [-999,1]
PRI_tau_pt                    PRI_tau_pt                    PRI_tau_pt                    PRI_tau_pt                                                      'F'    [20,384.756011963]
PRI_tau_eta                   PRI_tau_eta                   PRI_tau_eta                   PRI_tau_eta                                                     'F'    [-2.49300003052,2.492000103]
PRI_tau_phi                   PRI_tau_phi                   PRI_tau_phi                   PRI_tau_phi                                                     'F'    [-3.14199995995,3.14100003242]
PRI_lep_pt                    PRI_lep_pt                    PRI_lep_pt                    PRI_lep_pt                                                      'F'    [26,423.437988281]
PRI_lep_eta                   PRI_lep_eta                   PRI_lep_eta                   PRI_lep_eta                                                     'F'    [-2.49000000954,2.49000000954]
PRI_lep_phi                   PRI_lep_phi                   PRI_lep_phi                   PRI_lep_phi                                                     'F'    [-3.14100003242,3.14199995995]
PRI_met                       PRI_met                       PRI_met                       PRI_met                                                         'F'    [0.20000000298,551.059997559]
PRI_met_phi                   PRI_met_phi                   PRI_met_phi                   PRI_met_phi                                                     'F'    [-3.14100003242,3.14199995995]
PRI_met_sumet                 PRI_met_sumet                 PRI_met_sumet                 PRI_met_sumet                                                   'F'    [13.6780004501,1493.15405273]
PRI_jet_num                   PRI_jet_num                   PRI_jet_num                   PRI_jet_num                                                     'F'    [0,3]
PRI_jet_leading_pt            PRI_jet_leading_pt            PRI_jet_leading_pt            PRI_jet_leading_pt                                              'F'    [-999,683.197998047]
PRI_jet_leading_eta           PRI_jet_leading_eta           PRI_jet_leading_eta           PRI_jet_leading_eta                                             'F'    [-999,4.47599983215]
PRI_jet_leading_phi           PRI_jet_leading_phi           PRI_jet_leading_phi           PRI_jet_leading_phi                                             'F'    [-999,3.1400001049]
PRI_jet_subleading_pt         PRI_jet_subleading_pt         PRI_jet_subleading_pt         PRI_jet_subleading_pt                                           'F'    [-999,557.179992676]
PRI_jet_subleading_eta        PRI_jet_subleading_eta        PRI_jet_subleading_eta        PRI_jet_subleading_eta                                          'F'    [-999,4.47200012207]
PRI_jet_subleading_phi        PRI_jet_subleading_phi        PRI_jet_subleading_phi        PRI_jet_subleading_phi                                          'F'    [-999,3.14100003242]
PRI_jet_all_pt                PRI_jet_all_pt                PRI_jet_all_pt                PRI_jet_all_pt                                                  'F'    [-0,1264.44604492]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadFisher : public IClassifierReader {

 public:

   // constructor
   ReadFisher( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadFisher" ),
        fNvars( 30 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "DER_mass_MMC", "DER_mass_transverse_met_lep", "DER_mass_vis", "DER_pt_h", "DER_deltaeta_jet_jet", "DER_mass_jet_jet", "DER_prodeta_jet_jet", "DER_deltar_tau_lep", "DER_pt_tot", "DER_sum_pt", "DER_pt_ratio_lep_tau", "DER_met_phi_centrality", "DER_lep_eta_centrality", "PRI_tau_pt", "PRI_tau_eta", "PRI_tau_phi", "PRI_lep_pt", "PRI_lep_eta", "PRI_lep_phi", "PRI_met", "PRI_met_phi", "PRI_met_sumet", "PRI_jet_num", "PRI_jet_leading_pt", "PRI_jet_leading_eta", "PRI_jet_leading_phi", "PRI_jet_subleading_pt", "PRI_jet_subleading_eta", "PRI_jet_subleading_phi", "PRI_jet_all_pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadFisher() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[30];
   double fVmax[30];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[30];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   double              fFisher0;
   std::vector<double> fFisherCoefficients;
};

inline void ReadFisher::Initialize() 
{
   fFisher0 = -0.365802535643;
   fFisherCoefficients.push_back( 9.16765560853e-05 );
   fFisherCoefficients.push_back( -0.00870577924078 );
   fFisherCoefficients.push_back( -0.00974318889448 );
   fFisherCoefficients.push_back( 0.000213250200478 );
   fFisherCoefficients.push_back( 0.0648706427254 );
   fFisherCoefficients.push_back( 0.000153339621134 );
   fFisherCoefficients.push_back( 0.00635384528266 );
   fFisherCoefficients.push_back( 0.474187828032 );
   fFisherCoefficients.push_back( 0.00123638971725 );
   fFisherCoefficients.push_back( -6.71955602989 );
   fFisherCoefficients.push_back( -0.343025447377 );
   fFisherCoefficients.push_back( 0.0737498033301 );
   fFisherCoefficients.push_back( -0.0613684118714 );
   fFisherCoefficients.push_back( 6.72750894353 );
   fFisherCoefficients.push_back( -0.00207735772233 );
   fFisherCoefficients.push_back( -0.00170897153911 );
   fFisherCoefficients.push_back( 6.73513463512 );
   fFisherCoefficients.push_back( -0.00146437516304 );
   fFisherCoefficients.push_back( -0.00618489704809 );
   fFisherCoefficients.push_back( 3.74278889197e-05 );
   fFisherCoefficients.push_back( 0.00406286202706 );
   fFisherCoefficients.push_back( 0.000712723552521 );
   fFisherCoefficients.push_back( -0.0603812587188 );
   fFisherCoefficients.push_back( 0.000953026298317 );
   fFisherCoefficients.push_back( -0.00231389474421 );
   fFisherCoefficients.push_back( 0.00148125420806 );
   fFisherCoefficients.push_back( -0.00154679528531 );
   fFisherCoefficients.push_back( -0.000461289072163 );
   fFisherCoefficients.push_back( -0.00783495502438 );
   fFisherCoefficients.push_back( 6.71825251728 );

   // sanity check
   if (fFisherCoefficients.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fFisherCoefficients.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadFisher::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fFisher0;
   for (size_t ivar = 0; ivar < fNvars; ivar++) {
      retval += fFisherCoefficients[ivar]*inputValues[ivar];
   }

   return retval;
}

// Clean up
inline void ReadFisher::Clear() 
{
   // clear coefficients
   fFisherCoefficients.clear(); 
}
   inline double ReadFisher::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
